INFO     cardano_node_tests.tests.conftest:conftest.py:136 Changed CWD to '/home/martink/Source/repos/cardano-node-tests2/tmp/pytest-of-martink/pytest-326/popen-gw2'.
INFO     cardano_node_tests.utils.cluster_management:cluster_management.py:444 Stopping cluster with `/home/martink/Source/repos/cardano-node-tests2/tmp/pytest-of-martink/pytest-326/cluster5/startup_files/exprvfwo/stop-cluster-hfc`.
INFO     cardano_node_tests.utils.artifacts:artifacts.py:44 Start script coverage log file saved to '/home/martink/Source/repos/cardano-node-tests2/.cli_coverage/cli_coverage_script_220808_003244182_cnli.log'.
INFO     cardano_node_tests.utils.artifacts:artifacts.py:80 Cluster artifacts saved to '/home/martink/Source/repos/cardano-node-tests2/tmp/pytest-of-martink/pytest-326/cluster_artifacts/state-cluster5_jpcfhlpc'.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:353 Starting cluster with `/home/martink/Source/repos/cardano-node-tests2/tmp/pytest-of-martink/pytest-326/cluster5/startup_files/exprvfwo/start-cluster-hfc`.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:355 Cluster started.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:377 Performing 'restart' action on services ['nodes:pool2', 'nodes:pool3'].
INFO     cardano_node_tests.tests.test_kes:test_kes.py:245 2022-08-08 00:56:47.444878: Waiting for 200 sec for KES expiration.
INFO     cardano_node_tests.tests.test_kes:test_kes.py:249 2022-08-08 01:00:07.545004: KES expired (?); tip: '{'block': 778, 'epoch': 8, 'era': 'Babbage', 'hash': '4eb049700d41973fae8e1f56c971538fcbabb43af5eb7b50111c6b67ef11a489', 'slot': 7285, 'syncProgress': 100.0}'.
INFO     cardano_node_tests.tests.test_kes:test_kes.py:130 2022-08-08 01:00:07.581644: Waiting for 1 new epoch(s).
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:3045 Waiting for 164.00 sec for slot no 8105.
INFO     cardano_node_tests.tests.test_kes:test_kes.py:133 2022-08-08 01:02:54.960807: Waiting for the end of current epoch.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:377 Performing 'restart' action on services ['nodes:pool2', 'nodes:pool3'].
INFO     cardano_node_tests.tests.test_kes:test_kes.py:267 2022-08-08 01:05:58.631878: Waiting 120 secs to make sure the expected errors make it to log files.