INFO     cardano_node_tests.tests.conftest:conftest.py:135 Changed CWD to '/home/martink/Source/repos/cardano-node-tests5/tmp/pytest-of-martink/pytest-31/popen-gw2'.
INFO     cardano_node_tests.utils.cluster_management:cluster_management.py:443 Stopping cluster with `/home/martink/Source/repos/cardano-node-tests5/tmp/pytest-of-martink/pytest-31/cluster8/startup_files/pwyydmpt/stop-cluster-hfc`.
INFO     cardano_node_tests.utils.artifacts:artifacts.py:44 Start script coverage log file saved to '/home/martink/Source/repos/cardano-node-tests5/.cli_coverage/cli_coverage_script_220725_152200852_jomi.log'.
INFO     cardano_node_tests.utils.artifacts:artifacts.py:80 Cluster artifacts saved to '/home/martink/Source/repos/cardano-node-tests5/tmp/pytest-of-martink/pytest-31/cluster_artifacts/state-cluster8_dqujbpbt'.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:344 Starting cluster with `/home/martink/Source/repos/cardano-node-tests5/tmp/pytest-of-martink/pytest-31/cluster8/startup_files/pwyydmpt/start-cluster-hfc`.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:346 Cluster started.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:368 Performing 'restart' action on services ['nodes:pool2', 'nodes:pool3'].
INFO     cardano_node_tests.tests.test_kes:test_kes.py:245 2022-07-25 15:39:10.053364: Waiting for 200 sec for KES expiration.
INFO     cardano_node_tests.tests.test_kes:test_kes.py:249 2022-07-25 15:42:30.153451: KES expired (?); tip: '{'block': 564, 'epoch': 6, 'era': 'Alonzo', 'hash': '52dd12dd747165ff6b53c838cc22623cc51234425b915f35c8be06235bb5f56f', 'slot': 5202, 'syncProgress': '100.00'}'.
INFO     cardano_node_tests.tests.test_kes:test_kes.py:130 2022-07-25 15:42:30.189704: Waiting for 1 new epoch(s).
INFO     cardano_clusterlib.clusterlib_klass:clusterlib_klass.py:3099 Waiting for 180.60 sec for slot no 6105.
INFO     cardano_node_tests.tests.test_kes:test_kes.py:133 2022-07-25 15:45:30.976322: Waiting for the end of current epoch.
INFO     cardano_node_tests.utils.cluster_nodes:cluster_nodes.py:368 Performing 'restart' action on services ['nodes:pool2', 'nodes:pool3'].
INFO     cardano_node_tests.tests.test_kes:test_kes.py:267 2022-07-25 15:48:33.449661: Waiting 120 secs to make sure the expected errors make it to log files.